[package]
name = "yasfw"
version = "0.1.0"
authors = ["DDoSolitary <DDoSolitary@gmail.com>"]
edition = "2018"
build = "build.rs"
description = "Yet Another SSHFS for Windows"

[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"
lto = true

[build-dependencies]
winapi = { version = "0.3.8", features = ["winnt"] }
winres = "0.1.11"

[dependencies]
bitflags = "1.2.1"
clap = "2.33.0"
ctrlc = "3.1.3"
lazy_static = "1.4.0"
libc = "0.2.66"
lru = "0.4.3"
rpassword = "4.0.4"
slog = { version = "2.5.2", features = ["max_level_trace"] }
slog-async = "2.3.0"
slog-term = "2.4.2"
widestring = "0.4.0"
winapi = { version = "0.3.8", features = ["std", "winbase", "minwinbase", "ntdef", "ntstatus", "winnt", "fileapi"] }
