on: push
jobs:
  build:
    strategy:
      matrix:
        rust_triplet: [x86_64-pc-windows-msvc, i686-pc-windows-msvc]
        include:
          - rust_triplet: x86_64-pc-windows-msvc
            vcpkg_triplet: x64-windows-static
            arch: x86_64
            abi: msvc
          - rust_triplet: i686-pc-windows-msvc
            vcpkg_triplet: x86-windows-static
            arch: i686
            abi: msvc
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - env:
          VCPKG_DEFAULT_TRIPLET: ${{ matrix.vcpkg_triplet }}
          RUSTFLAGS: -Ctarget-feature=+crt-static
        run: |
          pushd $Env:VCPKG_INSTALLATION_ROOT
          cmd /c "git pull 2>&1"
          .\bootstrap-vcpkg.bat
          popd
          vcpkg integrate install
          vcpkg install libssh

          cmd /c "rustup toolchain install stable-${{ matrix.rust_triplet }} 2>&1"
          cmd /c "git fetch --tags --unshallow 2>&1"
          $Env:DOKAN_DLL_OUTPUT_PATH = $PWD
          cmd /c "cargo +stable-${{ matrix.rust_triplet }} build --release --target ${{ matrix.rust_triplet }} 2>&1"
          if ($LASTEXITCODE -ne 0) { exit 1 }

          7z a release.zip `
              .\LICENSE `
              .\dokan1.dll `
              .\target\${{ matrix.rust_triplet }}\release\yasfw.exe `

          curl.exe -fsS -T release.zip -u ddosolitary:${{ secrets.BINTRAY_KEY }} https://api.bintray.com/content/ddosolitary/dev-releases/default/default/yasfw/yasfw-$(git describe --tags)-${{ matrix.arch }}-${{ matrix.abi }}.zip
          curl.exe -fsS -X POST -u ddosolitary:${{ secrets.BINTRAY_KEY }} https://api.bintray.com/content/ddosolitary/dev-releases/default/default/publish
